# Generated by Django 3.0.8 on 2021-11-03 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0002_auto_20211103_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='promedio_final',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Sólo se permiten números.')]),
        ),
    ]
