# Generated by Django 3.0.8 on 2021-11-04 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0003_auto_20211103_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='calle',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Sólo se permiten códigos postales válidos.')]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='colonia',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('', 'Seleccione...'), ('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sse_app.Estados'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sse_app.Municipios'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='promedio_final',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+(\\.[0-9]{1,4})?$', 'Sólo se permiten números con el formato: X.XX')]),
        ),
    ]
