# Generated by Django 3.0.8 on 2021-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0005_auto_20211104_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Seleccione género'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True),
        ),
    ]
