# Generated by Django 3.0.8 on 2021-11-04 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0006_auto_20211104_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Sólo se permiten caracteres alfanuméricos.')]),
        ),
    ]
