# Generated by Django 3.0.8 on 2021-11-05 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sse_app', '0009_auto_20211105_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleoinmediato',
            name='correo_empleo_inmediato',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$', 'Sólo se permiten direcciones de e-mail válidas.')]),
        ),
        migrations.AlterField(
            model_name='empleoinmediato',
            name='matricula',
            field=models.ForeignKey(blank=True, db_column='matricula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sse_app.Alumno', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Sólo se permiten caracteres alfanuméricos.')]),
        ),
        migrations.AlterField(
            model_name='empleoinmediato',
            name='puesto_empleo_inmediato',
            field=models.CharField(blank=True, choices=[('', 'Seleccione...'), ('Director general', 'Director general'), ('Dueño o socio de empresa, despacho, rancho', 'Dueño o socio de empresa, despacho, rancho'), ('Profesional independiente', 'Profesional independiente'), ('Gerente/Director de área', 'Gerente/Director de área'), ('Subgerente/Subdirector de área', 'Subgerente/Subdirector de área'), ('Jefe de departamento', 'Jefe de departamento'), ('Ejecutivo de Cuenta', 'Ejecutivo de Cuenta'), ('Jefe de oficina/sección/área', 'Jefe de oficina/sección/área'), ('Empleado profesional', 'Empleado profesional'), ('Supervisor', 'Supervisor'), ('Analista especializado/técnico', 'Analista especializado/técnico'), ('Profesional independiente', 'Profesional independiente'), ('Gerente/Director de área', 'Gerente/Director de área'), ('Subgerente/Subdirector de área', 'Subgerente/Subdirector de área'), ('Jefe de departamento', 'Jefe de departamento'), ('Ejecutivo de Cuenta', 'Ejecutivo de Cuenta'), ('Jefe de oficina/sección/área', 'Jefe de oficina/sección/área'), ('Empleado profesional', 'Empleado profesional'), ('Supervisor', 'Supervisor'), ('Analista especializado/técnico', 'Analista especializado/técnico'), ('Vendedor en establecimiento', 'Vendedor en establecimiento'), ('Asistente', 'Asistente'), ('Ayudante', 'Ayudante'), ('Por cuenta propia no profesional', 'Por cuenta propia no profesional'), ('Empleado no profesional', 'Empleado no profesional'), ('Auxiliar', 'Auxiliar'), ('Otro', 'Otro')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='empleoinmediato',
            name='telefono_empleo_inmediato',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Sólo se permiten números de teléfono de 10 dígitos.')]),
        ),
    ]
